# This is a basic workflow to help you get started with Actions

name: CI-CD for main

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Runs a single command using the runners shell
      - name: Echo GITHUB_WORSPACE
        run: echo $GITHUB_WORKSPACE
      
      # Executing the linting checks
      # linting can be added via the following command
      - name: linting checks
        run: cd $GITHUB_WORKSPACE && npm i && npm run lint
      
      # starting mongoDB
      - name: Start MongoDB ${{ matrix.mongodb-version }}
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      
      # Executing the integration tests
      # unit tests can be executed via the following command
      - name: Integration tests checks
        run: |
          cd $GITHUB_WORKSPACE && npm i 
          npm run start
          npm run test
          kill -9 `lsof -i:3000 -t`

  deploy:
    # dependency on previous step
    needs: [build]
    
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:    
      - name: execute git command
        run: git filter-branch -- --all

      - name: Deploy to Heroku
        # You may pin to the exact commit or the version.
        # uses: AkhileshNS/heroku-deploy@79ef2ae4ff9b897010907016b268fd0f88561820
        uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          # This will be used for authentication. You can find it in your heroku homepage account settings
          heroku_api_key: ${{ secrets.HEROKU_SECRET_KEY }}
          # The appname to use for deploying/updating
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          # Email that you use with heroku
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
